CREATE TYPE ordering_status_enum AS ENUM ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'COMPLETED');
CREATE TYPE transaction_status_enum AS ENUM ('UNPAID', 'PAID', 'FAILED', 'CANCELLED');
CREATE TYPE kurir_enum AS ENUM ('JNE', 'JNT', 'GO-SEND', 'SHOPEE EXPRESS');

CREATE TABLE "ordering" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consumer" integer NOT NULL,
  "date" timestamptz NOT NULL,
  "notes" varchar NOT NULL,
  "status" ordering_status_enum DEFAULT 'PENDING' NOT NULL,
  "kurir" kurir_enum NOT NULL,
  "alamat" varchar NOT NULL,
  "invoice_url" varchar NOT NULL,
  "latitude" DOUBLE PRECISION NOT NULL,
  "longitude" DOUBLE PRECISION NOT NULL
);

CREATE TABLE "detail_ordering" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consumer" integer NOT NULL,
  "id_ordering" integer NOT NULL,
  "id_fish" integer NOT NULL,
  "weight" integer NOT NULL
);

CREATE TABLE "transaction" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_external" varchar NOT NULL,
  "id_consumer" integer NOT NULL,
  "id_ordering" integer NOT NULL,
  "dates_transaction" timestamptz NOT NULL,
  "dates_payed" timestamptz NOT NULL,
  "status" transaction_status_enum DEFAULT 'UNPAID' NOT NULL
);

CREATE TABLE "cart" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consumer" integer NOT NULL,
  "id_fish" integer NOT NULL,
  "notes" varchar NOT NULL,
  "weight" integer NOT NULL
);

CREATE TABLE "fish" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_seller" integer NOT NULL,
  "id_weight" integer NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "price" numeric(10, 2) NOT NULL,
  "photo_url" varchar NOT NULL
);

CREATE TABLE "weight" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "weight" integer NOT NULL
);

CREATE TABLE "seller" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar NOT NULL UNIQUE,
  "password" varchar NOT NULL,
  "role" varchar DEFAULT 'SELLER' NOT NULL,
  "phone_number" varchar NOT NULL,
  "location" varchar NOT NULL,
  "address" varchar NOT NULL
);

CREATE TABLE "consumer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar NOT NULL UNIQUE,
  "password" varchar NOT NULL,
  "role" varchar DEFAULT 'CONSUMER' NOT NULL,
  "phone_number" varchar NOT NULL,
  "address" varchar NOT NULL
);

ALTER TABLE "fish" ADD FOREIGN KEY ("id_weight") REFERENCES "weight" ("id");
ALTER TABLE "fish" ADD FOREIGN KEY ("id_seller") REFERENCES "seller" ("id");

ALTER TABLE "cart" ADD FOREIGN KEY ("id_fish") REFERENCES "fish" ("id");
ALTER TABLE "cart" ADD FOREIGN KEY ("id_consumer") REFERENCES "consumer" ("id");

ALTER TABLE "ordering" ADD FOREIGN KEY ("id_consumer") REFERENCES "consumer" ("id");

ALTER TABLE "detail_ordering" ADD FOREIGN KEY ("id_consumer") REFERENCES "consumer" ("id");
ALTER TABLE "detail_ordering" ADD FOREIGN KEY ("id_fish") REFERENCES "fish" ("id");
ALTER TABLE "detail_ordering" ADD FOREIGN KEY ("id_ordering") REFERENCES "ordering" ("id");

ALTER TABLE "transaction" ADD FOREIGN KEY ("id_consumer") REFERENCES "consumer" ("id");
ALTER TABLE "transaction" ADD FOREIGN KEY ("id_ordering") REFERENCES "ordering" ("id");

CREATE INDEX idx_ordering_id_consumer ON ordering(id_consumer);
CREATE INDEX idx_ordering_status ON ordering(status);

CREATE INDEX idx_detail_ordering_id_consumer ON detail_ordering(id_consumer);
CREATE INDEX idx_transaction_id_ordering ON transaction(id_ordering);
CREATE INDEX idx_transaction_status ON transaction(status);

CREATE INDEX idx_detail_ordering_id_ordering ON detail_ordering(id_ordering);
CREATE INDEX idx_detail_ordering_id_fish ON detail_ordering(id_fish);

CREATE INDEX idx_transaction_id_consumer ON transaction(id_consumer);

CREATE INDEX idx_cart_id_consumer ON cart(id_consumer);
CREATE INDEX idx_cart_id_fish ON cart(id_fish);

CREATE INDEX idx_fish_id_seller ON fish(id_seller);
CREATE INDEX idx_fish_id_weight ON fish(id_weight);

CREATE UNIQUE INDEX idx_consumer_email ON consumer(email);

CREATE UNIQUE INDEX idx_seller_email ON seller(email);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_fish_name_trgm ON fish USING GIN (name gin_trgm_ops);